# Generated by Django 5.2.5 on 2026-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_comment_follow_quizrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquest",
            name="category",
            field=models.CharField(default="General", max_length=50),
        ),
    ]
