# Generated by Django 5.2.5 on 2026-05-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_question_image_question_time_limit_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="match_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="choice",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ", "Multiple Choice"),
                    ("TF", "True/False"),
                    ("ORDER", "Ordering"),
                    ("MATCH", "Matching"),
                ],
                default="MCQ",
                max_length=10,
            ),
        ),
    ]
