# Generated by Django 5.2.5 on 2026-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_choice_match_text_choice_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="max_streak",
            field=models.IntegerField(default=0),
        ),
    ]
