# Generated by Django 5.2.5 on 2026-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_profile_max_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="answer_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
